version: "3.8"

services:
  nginx:
    build:
      context: ./requirements/nginx
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "443:443"
    restart: always
    environment:
      - NGINX_HOST=lgreau.42.fr
    secrets:
      - db_password

  mariadb:
    build:
      context: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: /run/secrets/db_password
    volumes:
      - /home/lgreau/data/db:/var/lib/mysql
    restart: always
    secrets:
      - db_password

  wordpress:
    build:
      context: ./requirements/wordpress
    volumes:
      - /home/lgreau/data/wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: /run/secrets/db_password
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
    restart: always
    secrets:
      - db_password

secrets:
  db_password:
    file: ./../secrets/db_password.txt
  db_root_password:
    file: ./../secrets/db_root_password.txt
  credentials:
    file: ./../secrets/credentials.txt

volumes:
  db_data:
  wp_data:
