version: "3.8"

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    volumes:
      - wp_data:/var/www/html
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "443:443"
    restart: always
    environment:
      - NGINX_HOST=localhost
    secrets:
      - db_password
    networks:
      - inception_network

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    environment:
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER: ${WP_DB_USER}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  wordpress:
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    build:
      context: ./requirements/wordpress
    volumes:
      - wp_data:/var/www/html
    environment:
      WP_DB_HOST: mariadb:3306
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_USER_EMAIL: ${WP_DB_USER_EMAIL}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    restart: always
    secrets:
      - db_password
    networks:
      - inception_network

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./data/mysql
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: ./data/wordpress
      o: bind

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  credentials:
    file: ./secrets/credentials.txt

networks:
  inception_network:
    driver: bridge
