services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    volumes:
      - wp_data:/var/www/html
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "443:443"
    restart: always
    secrets:
      - db_password
    networks:
      - inception_network

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    environment:
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER: ${WP_DB_USER}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception_network

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    volumes:
      - wp_data:/var/www/html
    environment:
      WP_DB_HOST: mariadb:3306
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_USER_EMAIL: ${WP_DB_USER_EMAIL}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    restart: always
    secrets:
      - db_password
    networks:
      - inception_network

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/lgreau/data/mysql
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/lgreau/data/wordpress
      o: bind

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt

networks:
  inception_network:
    driver: bridge
